version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: neo4flix-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./neo4flix.conf:/etc/nginx/conf.d/default.conf
      - ../ssl-certs/neo4flix-cert.pem:/etc/nginx/ssl/neo4flix-cert.pem
      - ../ssl-certs/neo4flix-key.pem:/etc/nginx/ssl/neo4flix-key.pem
      - certbot-webroot:/var/www/certbot
    networks:
      - neo4flix-network
    restart: unless-stopped
    depends_on:
      - gateway

  certbot:
    image: certbot/certbot
    container_name: neo4flix-certbot
    volumes:
      - certbot-webroot:/var/www/certbot
      - certbot-certs:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - neo4flix-network

volumes:
  certbot-webroot:
  certbot-certs:

networks:
  neo4flix-network:
    external: true
